version: '3'
services:
  discord-bot:
    restart: always
    build: .
    container_name: 'discord-bot-python'
    working_dir: '/root/opt'
    tty: true
    volumes:
      - ./opt:/root/opt
    command: [ python, discordBot.py ]